### ISSUE TITLE
FEATURE: Variable lifetime in lua

### ISSUE THREAD

**Issue by lucasdpt** [Sinan-Karakaya/R-Type#119]
**Is your feature request related to a problem? Please describe.**
We cannot keep variable ;(

**Describe the solution you'd like**
We need to be able to keep the state of variable declared inside a lua script for purposes such as stats.

**Comment by Sinan-Karakaya** [comment]
After some research, it doesn't look like an easy method is possible. This will need more research and tries as getting this feature would be very useful, but for now, we are lowering its priority.

**Comment by lucasdpt** [comment]
A little implementation of this in #136
