### ISSUE TITLE
Failed to open X11 display

### ISSUE THREAD

**Issue by lucasdpt** [Sinan-Karakaya/R-Type#75]
**Describe the bug**
When we want to start the server headless, it does not want to and gives this error:
![image](https://github.com/Sinan-Karakaya/R-Type/assets/34922832/daee2c07-3c97-4396-8c49-94e4a930bc16)

**To Reproduce**
1. Get a env without display
2. Launch serveur
3. See error

**Expected behavior**
Server start normally

**Desktop (please complete the following information):**
 - OS: Debian
 - Version: 11
 - Headless

**Comment by Sinan-Karakaya** [comment]
This will likely be fixed with #76. Closing to avoid duplicate.
